### PR TITLE
Configure autoreply on company interest mails

### PR DESCRIPTION
**Pull request by juniwbjerde**
Bedkom wanted an automatic mail confirming that their attempt to contact us was successful to be sent to a company when they send in a company interest form, so that is what this PR aims to achieve.

### CODE REVIEW

**Comment by ivarnakken** [comment]
What's the status on this? As these mails are quite important, extensive tests should be written 😄

**Comment by juniwbjerde** [comment]
I talked with bedkom at couple of days ago and they wanted a few changes, so i'm working on implementing that now! I agree that it's quite important, so tests should indeed be written, but it's not all that easy to test email stuff. I know @theodorsm had the same problem with testing the deletion of users functionality recently, so i'll talk to him about how he ended up solving it:)

**Comment by ivarnakken** [comment]
>  but it's not all that easy to test email stuff. 

There are already a bunch of mail tests you can `kok` :)

**Comment by juniwbjerde** [comment]
I'll have to finish the tests later on.

**Pull request merged**
