### PR TITLE
Auto theme option

### PR DESCRIPTION
**Pull request by Mathiazom**
Solves #2000 

See https://github.com/webkom/lego-webapp/pull/2191 for frontend PR

### CODE REVIEW

**Review by LudvigHz — APPROVED** [review]
LGTM :shipit: 

Sidenote: If you add your GPG signing key to your github account your commits will actually be verified by GitHub!

**Review by odinuge — APPROVED** [review]
lgtm

I vote for updating the default as well. https://github.com/webkom/lego/blob/907684f2bfe9704477863ceef083a66c8ef16dc7/lego/apps/users/models.py#L336

**Comment by Mathiazom** [comment]
> Sidenote: If you add your GPG signing key to your github account your commits will actually be verified by GitHub!

I have, but Github does not seem to care about multiple emails in the same key and checks the wrong one 🤦

**Comment by odinuge** [comment]
> I have, but Github does not seem to care about multiple emails in the same key and checks the wrong one facepalm

Strange... I have the same setup, and it works for me..

```
$ curl https://github.com/Mathiazom.gpg | gpg          
gpg: WARNING: no command supplied.  Trying to guess what you mean ...
  % Total    % Received % Xferd  Average Speed   Time    Time     Time  Current
                                 Dload  Upload   Total   Spent    Left  Speed
100  3166  100  3166    0     0  12223      0 --:--:-- --:--:-- --:--:-- 12176
pub   rsa4096 2020-08-23 [SC]
      E521390C38340EE3A63923953464BADCE1277D56
uid           Mathias Oterhals Myklebust (Macbook) <mathiom@stud.ntnu.no>
sub   rsa4096 2020-08-23 [E]
$ curl https://github.com/odinuge.gpg | gpg  
gpg: WARNING: no command supplied.  Trying to guess what you mean ...
  % Total    % Received % Xferd  Average Speed   Time    Time     Time  Current
                                 Dload  Upload   Total   Spent    Left  Speed
100  7631  100  7631    0     0  30043      0 --:--:-- --:--:-- --:--:-- 29925
pub   rsa4096 2014-01-10 [SC]
      43FCA9395DB2DA04D1D29ADF49AEAB06408DD4C2
uid           Odin Ugedal <odin@ugedal.com>
uid           Odin Ugedal <odin@uged.al>
sub   rsa4096 2014-01-10 [E]
sub   rsa4096 2016-04-16 [S] [expires: 2044-01-24]
sub   rsa4096 2016-04-16 [A] [expires: 2044-01-24]
```

There is some strange stuff going on with github and updating gpg keys tho. It might work if you delete the key and then uploads it agian. I think that was what I did.

**Comment by Mathiazom** [comment]
> > I have, but Github does not seem to care about multiple emails in the same key and checks the wrong one facepalm
> 
> Strange... I have the same setup, and it works for me..
> 
> ```
> $ curl https://github.com/Mathiazom.gpg | gpg          
> gpg: WARNING: no command supplied.  Trying to guess what you mean ...
>   % Total    % Received % Xferd  Average Speed   Time    Time     Time  Current
>                                  Dload  Upload   Total   Spent    Left  Speed
> 100  3166  100  3166    0     0  12223      0 --:--:-- --:--:-- --:--:-- 12176
> pub   rsa4096 2020-08-23 [SC]
>       E521390C38340EE3A63923953464BADCE1277D56
> uid           Mathias Oterhals Myklebust (Macbook) <mathiom@stud.ntnu.no>
> sub   rsa4096 2020-08-23 [E]
> $ curl https://github.com/odinuge.gpg | gpg  
> gpg: WARNING: no command supplied.  Trying to guess what you mean ...
>   % Total    % Received % Xferd  Average Speed   Time    Time     Time  Current
>                                  Dload  Upload   Total   Spent    Left  Speed
> 100  7631  100  7631    0     0  30043      0 --:--:-- --:--:-- --:--:-- 29925
> pub   rsa4096 2014-01-10 [SC]
>       43FCA9395DB2DA04D1D29ADF49AEAB06408DD4C2
> uid           Odin Ugedal <odin@ugedal.com>
> uid           Odin Ugedal <odin@uged.al>
> sub   rsa4096 2014-01-10 [E]
> sub   rsa4096 2016-04-16 [S] [expires: 2044-01-24]
> sub   rsa4096 2016-04-16 [A] [expires: 2044-01-24]
> ```
> 
> There is some strange stuff going on with github and updating gpg keys tho. It might work if you delete the key and then uploads it agian. I think that was what I did.

Yup, that worked 💃

**Review by odinuge — APPROVED** [review]
Awesome!

**Pull request merged**
