### PR TITLE
Fix frontpage

### PR DESCRIPTION
**Pull request by odinuge**
This would benefit of some tests :tm:

### CODE REVIEW

**Comment by cherrybeans** [comment]
Is this the fix to why the frontpage is not working when not logged in?

**Comment by odinuge** [comment]
Yes sir

**Comment by cherrybeans** [comment]
What made it malfunction in the first place? Curious

**Comment by odinuge** [comment]
https://github.com/webkom/lego/pull/1466/files#diff-20e67ca57d33bd498ade43a5f610580cR73

:arrow_up: @cherrybeans

**Comment by cherrybeans** [comment]
Already saw that, not that smart though :disappointed:

**Comment by odinuge** [comment]
It is because `Registration.objects.filter(user=request.user)` isn't valid when the user isn't authenticated.

**Pull request merged**
