### PR TITLE
Add GitHub Actions workflow

### PR DESCRIPTION
**Pull request by kotlarz**
See [GitHub Actions workflow](https://github.com/webkom/lego/actions) for this repo, [here](https://github.com/webkom/lego/commit/c5898d629166fc82d7fb45840f7f66804cb38011/checks) is the latest workflow job for this PR.

Need to make it required in repo settings after merge:
image

### CODE REVIEW

**Comment by kotlarz** [comment]
Hold the merge!

Testing concurrent jobs.

**Comment by SmithPeder** [comment]
Workflows don't trigger anymore, I'll revert this until we can get it working again.

**Comment by SmithPeder** [comment]
Or nvm, maybe i'll wont
image

**Comment by SmithPeder** [comment]
#1696

**Pull request merged**
