### PR TITLE
Change default captcha key and verification site

### LINKED ISSUE #3005: Migrate from CAPTCHA to Turnstile
Turnstile
* is not from *Google*.
* doesn't force users to help train Google's car AI.
* easy (?) to [migrate to](https://developers.cloudflare.com/turnstile/get-started/migrating-from-recaptcha/).
* solves the stupid issue with showing captchas so early they expire (Bc. a Turnstile token is valid for 300 seconds).

Closes #2291

### PR DESCRIPTION
**Pull request by ollfkaih**
Closes #3005

### CODE REVIEW

**Comment by erlingfn** [comment]
I assume we have to wait for the frontend PR to be ready until we merge this?

**Comment by ollfkaih** [comment]
> I assume we have to wait for the frontend PR to be ready until we merge this?

Yes, or it will probably break CI.

**Comment by LudvigHz** [comment]
> > I assume we have to wait for the frontend PR to be ready until we merge this?
> 
> Yes, or it will probably break CI.

Well, won't it be the other way around?
We need to merge this before the frontend CI passes. The CI here does not have any tests for captcha, while the frontend E2E tests requires this in order to pass.

**Comment by ollfkaih** [comment]
> > > I assume we have to wait for the frontend PR to be ready until we merge this?
> > 
> > 
> > Yes, or it will probably break CI.
> 
> Well, won't it be the other way around? We need to merge this before the frontend CI passes. The CI here does not have any tests for captcha, while the frontend E2E tests requires this in order to pass.

But merging this will break all other frontend branches E2E in the meantime.

**Review by LudvigHz — APPROVED** [review]

**Pull request merged**
