### PR TITLE
Bump django from 3.0.14 to 3.2.9

### PR DESCRIPTION
**Pull request by LudvigHz**
Preliminary tests show everything working as it should. Also ran E2E tests on this branch, with all
tests passing.

There aren't really that many breaking changes in 3.2, at least none that are important in regards
to the apps functionality. So in theory this should work without any issues :tm:

### CODE REVIEW

**Review by SmithPeder — APPROVED** [review]
Looks Good

**Review by erlingfn — APPROVED** [review]
LGTM

**Review by ivarnakken — APPROVED** [review]
Nice 💯

**Review by PeterJFB — APPROVED** [review]
lgtm^

**Pull request merged**
